---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    driver_config:
      network:
        - ["forwarded_port", {guest: 8080, host: 58080}]
        - ["forwarded_port", {guest: 80, host: 8080}]
    run_list:
      - recipe[cylance-agent::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
