# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Prep Build Agent
  jobs:
  - job: Install ChefDK
    steps:
    - task: vsts-chef-task-install-chefdk@1
      displayName: 'Install ChefDK (Current)'
      inputs:
        chefDKForceInstall: true

# - stage: Test Cookbook
#   - task: vsts-chef-task-test-kitchen@1
#     displayName: 'Test Kitchen - converge'
#     inputs:
#       tkAzureEndpoint: 'Solutions Architecture(b02e675a-cee0-49bd-a056-daa7ed05bf4e)'
#       tkCommand: 'converge'
#       tkKitchenFile: '.kitchen.yml'
#
#
# - stage: Prep Build Agent
#   jobs:
#   - job: Install ChefDK
#     steps:
#     - task: vsts-chef-task-install-chefdk@1
#       displayName: 'Install ChefDK (Current)'
#       inputs:
#         chefDKForceInstall: true
#
#
#
#
#
#
#
#
#
#
# - task: vsts-chef-task-test-kitchen@1
#   displayName: 'Test Kitchen - converge'
#   inputs:
#     tkAzureEndpoint: 'Solutions Architecture(b02e675a-cee0-49bd-a056-daa7ed05bf4e)'
#     tkCommand: 'converge'
#     tkKitchenFile: '.kitchen.yml'
#
# - task: vsts-chef-task-test-kitchen@1
#   displayName: 'Test Kitchen - verify'
#   inputs:
#     tkAzureEndpoint: 'Solutions Architecture(b02e675a-cee0-49bd-a056-daa7ed05bf4e)'
#     tkCommand: 'verify'
#     tkKitchenFile: '.kitchen.yml'
#
# - task: vsts-chef-task-test-kitchen@1
#   displayName: 'Test Kitchen - destroy'
#   inputs:
#     tkAzureEndpoint: 'Solutions Architecture(b02e675a-cee0-49bd-a056-daa7ed05bf4e)'
#     tkCommand: 'destroy'
#     tkKitchenFile: '.kitchen.yml'
